import os

REDIS_URL = os.environ['REDIS_URL']
SLACK_WEBHOOK_URLS = os.environ['SLACK_WEBHOOK_URL'].split(',')
CHECK_INTERVAL = os.getenv('CHECK_INTERVAL', 60)
CHECK_INTERVAL = os.getenv('CHECK_INTERVAL', 60)
USE_EMOTICONS = os.getenv('USE_EMOTICONS', False)

TRUSTPILOT_BUSINESS_ID = os.getenv('TRUSTPILOT_BUSINESS_ID')
TRUSTPILOT_API_KEY = os.getenv('TRUSTPILOT_API_KEY')

FACEBOOK_ACCESS_TOKEN = os.getenv('FACEBOOK_ACCESS_TOKEN')
FACEBOOK_PAGE_ID = os.getenv('FACEBOOK_PAGE_ID')

TWITTER_APP_KEY = os.getenv('TWITTER_APP_KEY')
TWITTER_APP_SECRET = os.getenv('TWITTER_APP_SECRET')
TWITTER_SEARCH_KEYWORD = os.getenv('TWITTER_SEARCH_KEYWORD')

DEADMANSSNITCH_URL = os.getenv('DEADMANSSNITCH_URL')
